apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry-relay.fullname" . }}
  labels:
    {{- include "telemetry-relay.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.env | nindent 2 }}
