apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry-relay.fullname" . }}
  labels:
    {{- include "telemetry-relay.labels" . | nindent 4 }}
data:
  {{- toYaml (omit .Values.env "NUON_TELEMETRY_ENVIRONMENT_ENDPOINT") | nindent 2 }}
  NUON_TELEMETRY_ENVIRONMENT_ENDPOINT: {{ ternary "0.0.0.0:5318" "127.0.0.1:5318" .Values.environmentReceiver.enabled | quote }}
