apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "telemetry-relay.fullname" . }}
  labels:
    {{- include "telemetry-relay.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "telemetry-relay.selectorLabels" . | nindent 6 }}
