apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-relay.fullname" . }}
  labels:
    {{- include "telemetry-relay.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "telemetry-relay.selectorLabels" . | nindent 4 }}
  ports:
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: health
      port: 13133
      targetPort: health
