apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-agent.fullname" . }}
  labels:
    {{- include "telemetry-agent.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "telemetry-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
